const PREFIX = 'PICX_'

/**
 * LocalStorage Key
 */
export const LS_CONFIG = `${PREFIX}CONFIG`
export const LS_MANAGEMENT = `${PREFIX}MANAGEMENT`
export const LS_SETTINGS = `${PREFIX}SETTINGS`
export const LS_AUTHORIZATION = `${PREFIX}AUTHORIZATION`

/**
 * SessionStorage Key
 */
export const SS_GLOBAL_SETTINGS = `${PREFIX}GLOBAL_SETTINGS`
export const SS_CONFIG_TOKEN = `${PREFIX}CONFIG_TOKEN`
export const SS_AUTHORIZATION_SECRETS = `${PREFIX}AUTHORIZATION_SECRETS`
